<?php

    function dna_sequencer($input){
        $input_uc = strtoupper($input);
        $output = '';

        switch ($input_uc) {
            case 'A':
                $output = 'T';
                break;
            case 'T':
                $output = 'A';
                break;
            case 'C':
                $output = 'G';
                break;
            case 'G':
                $output = 'C';
                break;          
            default:
                $output = '';
                break;
        }
        return $output;
    }

