<?php

    function dna_sequencer($input){
        $input_uc = strtoupper($input);
        $output = '';

        switch ($input_uc) {
            case 'A':
                $output = 'T';
                break;
            case 'T':
                $output = 'A';
                break;            
            default:
                $output = '';
                break;
        }
        return $output;
    }

